import unittest
from test_mathfunc import TestMathFunc
from HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()

    # tests = [TestMathFunc("test_add"), TestMathFunc("test_minus"), TestMathFunc("test_divide")]
    # suite.addTests(tests)

    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))

    # with open('UnittestTestReport.txt', 'a') as f:
    #     runner = unittest.TextTestRunner(stream = f, verbosity=2)
    #     runner.run(suite)

    # 生成使用HTMLTestRunner生成HTML报告
    # 文件打开方式使用“w”会报错
    with open('HTMLReport.html', 'wb+') as fh:
        runner = HTMLTestRunner(stream=fh,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2)
        runner.run(suite)

