import os.path
import unittest
from datetime import datetime
from HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()

    # ************************** suite中添加case *********************************
    # https://blog.csdn.net/u011436666/article/details/73473013#t2
    # # 使用addTests组织用例
    # # 方法一：按照tests中执行
    # tests = [TestMathFunc("test_add"), TestMathFunc("test_minus"), TestMathFunc("test_divide")]
    # suite.addTests(tests)

    # # 方法二：与在tes_mathfunc.py中使用unittest.main()执行顺序一致
    # suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))

    # # 方法三：与在tes_mathfunc.py中使用unittest.main()执行顺序一致
    # case 所在路径
    proDir = os.path.split(os.path.realpath(__file__))[0]
    case_path = os.path.join(proDir, "testCase")
    # # 在指定的case所在的路径里寻找所有名称模式匹配pattern的文件并加载其内容
    print(case_path)
    discover = unittest.defaultTestLoader.discover(case_path, 'test*.py')
    # 遍历每个test*.py里面的case，并将其添加到TestSuite中
    for test_suite in discover:
        for test_case in test_suite:
            suite.addTest(test_case)

    # *****************************************************************************

    # **************************** runner ********************************************
    # ********************************************************************************
    # create result file
    resultPath = os.path.join(proDir, "result")
    if not os.path.exists(resultPath):
        os.mkdir(resultPath)
    # create report file
    reportPath = os.path.join(resultPath, str(datetime.now().strftime("%Y%m%d%H%M%S")))
    if not os.path.exists(reportPath):
        os.mkdir(reportPath)
    # *************************************************************************************

    # # 使用TextTestRunner执行runner,并执行
    # with open(os.path.join(reportPath, 'UnittestTestReport.txt'), 'a') as f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    # # 遍历
    #     runner.run(suite)
    # # 针对只有discover的情况
    #     # runner.run(discover)

    # # 使用HTMLTestRunner实例化runner,并执行
    # 生成使用HTMLTestRunner生成HTML报告
    # 文件打开方式使用“w”会报错
    with open(os.path.join(reportPath, 'HTMLReport.html'), 'wb+') as fh:
        runner = HTMLTestRunner(stream=fh,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2)
        runner.run(suite)
    # *******************************************************************************
